name: Update Azure VM passwords
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * 1' ##Runs at 9AM UTC every Monday##

permissions:
  id-token: write
  contents: read

jobs:
  rotatePwd:
    runs-on: windows-latest
    env:
      KEY_VAULT_NAME: 'your-key-vault-name'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3.0.2

    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Rotate VMs administrator passwords
      uses: Pwd9000-ML/azure-vm-password-rotate@v1.1.0
      with:
        key-vault-name: ${{ env.KEY_VAULT_NAME }}