name: Update Azure VM passwords
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * 1' ##Runs at 9AM UTC every Monday##

jobs:
  rotatePwd:
    runs-on: windows-latest
    env:
      KEY_VAULT_NAME: 'your-key-vault-name'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3.0.2

    - name: Log into Azure using github secret AZURE_CREDENTIALS
      uses: Azure/login@v1.4.5
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Rotate VMs administrator passwords
      uses: Pwd9000-ML/azure-vm-password-rotate@v1.1.0
      with:
        key-vault-name: ${{ env.KEY_VAULT_NAME }}